name: PlasAnn Windows Debug
on:
  push:
    branches: [ main, master, v1.1.0 ]
  pull_request:
    branches: [ main, master ]

jobs:
  debug-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ['3.9']
        
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Check files exist
      run: |
        dir
        echo "--- pyproject.toml ---"
        type pyproject.toml
        echo "--- plasann directory ---"
        dir plasann
        echo "--- __init__.py ---"
        type plasann\__init__.py
        
    - name: Try pip install with verbose output
      run: |
        echo "=== Upgrading pip ==="
        python -m pip install --upgrade pip
        echo "=== Installing with verbose output ==="
        pip install -v -e .
        echo "=== Checking what got installed ==="
        pip list
        pip show plasann
        
    - name: Test basic import
      run: |
        echo "=== Python version ==="
        python --version
        echo "=== Python path ==="
        python -c "import sys; [print(p) for p in sys.path]"
        echo "=== Try import ==="
        python -c "import plasann; print('SUCCESS:', plasann.__file__)"
        
  test-unix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9']
        
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install and test (for comparison)
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        python -c "import plasann; print('SUCCESS:', plasann.__file__)"
