name: Test PlasAnn Tool

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: "3.10"
          activate-environment: plasann-env
          channels: conda-forge,bioconda,defaults
          channel-priority: strict

      - name: Install dependencies (Ubuntu)
        if: runner.os == 'Linux'
        shell: bash -l {0}
        run: |
          sudo apt-get update
          sudo apt-get install -y ncbi-blast+ prodigal infernal

      - name: Install dependencies (macOS)
        if: runner.os == 'macOS'
        shell: bash -l {0}
        run: |
          brew update
          brew install blast prodigal
          brew tap brewsci/bio
          brew install infernal

      - name: Skip dependency install on Windows
        if: runner.os == 'Windows'
        run: echo "Skipping dependency installation on Windows due to unsupported packages."

      - name: Install PlasAnn
        if: runner.os != 'Windows'
        shell: bash -l {0}
        run: |
          pip install .

      - name: Debug directory listing
        continue-on-error: true
        shell: bash -l {0}
        run: |
          echo "=== Current directory ==="
          pwd
          echo "=== Git commit ==="
          git rev-parse HEAD
          echo "=== Directory listing ==="
          ls -la
          echo "=== Check plasann ==="
          ls plasann || echo "plasann folder not found"

      - name: Run PlasAnn help command
        if: runner.os != 'Windows'
        shell: bash -l {0}
        run: |
          PlasAnn --help
