name: Test PlasAnn Tool

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ncbi-blast+ prodigal infernal

      - name: Install PlasAnn
        run: |
          pip install .

      - name: Run basic command test
        run: |
          PlasAnn --help

