name: Test PlasAnn Tool

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies on Ubuntu
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y ncbi-blast+ prodigal infernal

      - name: Install dependencies on macOS
        if: runner.os == 'macOS'
        run: |
          brew update
          brew install blast prodigal
          brew tap brewsci/bio
          brew install infernal

      - name: Install PlasAnn
        run: |
          pip install .

      - name: Run tool check on Linux/macOS
        if: runner.os != 'Windows'
        run: |
          PlasAnn --help

      - name: Windows test (install only)
        if: runner.os == 'Windows'
        run: |
          echo "Windows test passed: PlasAnn installed successfully."

