name: Test PlasAnn Tool

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: "3.10"
          activate-environment: plasann-env
          environment-file: ""
          channels: conda-forge,bioconda,defaults
          channel-priority: strict

      - name: Install dependencies (Ubuntu)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y ncbi-blast+ prodigal infernal

      - name: Install dependencies (macOS)
        if: runner.os == 'macOS'
        run: |
          brew update
          brew install blast prodigal
          brew tap brewsci/bio
          brew install infernal

      - name: Install dependencies (Windows via Conda)
        if: runner.os == 'Windows'
        shell: bash -l {0}
        run: |
          conda install -y -c bioconda -c conda-forge blast prodigal infernal

      - name: Install PlasAnn
        shell: bash -l {0}
        run: |
          pip install .

      - name: Debug: directory listing
        continue-on-error: true
        run: |
          echo "=== Current directory ==="
          pwd
          echo "=== Git commit ==="
          git rev-parse HEAD
          echo "=== Directory listing (case sensitive) ==="
          ls -la
          echo "=== Looking for plasann directory ==="
          ls -la | grep -i plasann || echo "No plasann directory found"
          echo "=== Checking different case variations ==="
          test -d plasann && echo "plasann (lowercase) exists"
          test -d Plasann && echo "Plasann (capital P) exists"
          test -d PlasAnn && echo "PlasAnn (camel case) exists"
          test -d PLASANN && echo "PLASANN (uppercase) exists"

      - name: Run PlasAnn help command
        shell: bash -l {0}
        run: |
          PlasAnn --help

