name: Test PlasAnn Tool

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install system dependencies (Linux/macOS)
        if: runner.os != 'Windows'
        run: |
          sudo apt-get update || brew update
          sudo apt-get install -y ncbi-blast+ prodigal infernal || brew install blast prodigal infernal

      - name: Install PlasAnn
        run: |
          pip install .

      - name: Run tool check (Linux/macOS)
        if: runner.os != 'Windows'
        run: |
          PlasAnn --help

      - name: Windows test (install only)
        if: runner.os == 'Windows'
        run: |
          echo "Windows test passed: PlasAnn installed successfully."

